### ISSUE TITLE
Nested form fields?

### ISSUE THREAD

**Issue by pheuter** [rescriptbr/reform#210]
```res
type address = {
  line1: string,
  line2: option<string>,
  zip: int,
}

module FormFields = %lenses(
  type state = {
    name: string,
    email: string,
    address: address,
  }
)
```

Is it possible for lenses to support nested records? It doesn't seem like it's possible to make it work with reform:

```res
<input
  className="input"
  value={form.values.address.line2->Belt_Option.getWithDefault("")}
  onChange={ReForm.Helpers.handleChange(form.handleChange(FormFields.Address))}
  type_="text"
/>
```

Is this even a valid way to think about the use case? Should all form fields be top-level by design? Any guidance or feedback appreciated.

**Comment by fakenickels** [comment]
unfortunately it's not possible currently and we haven't thought of a good way to make it

buuut what we've been doing for is to treat nested data as nested forms, so we create a new "ReForm instance" for every

```rescript
module AddressState = %lenses(
type state = {
  line1: string,
  line2: option<string>,
  zip: int,
}
)

module FormFields = %lenses(
  type state = {
    name: string,
    email: string,
    address: AddressState.state,
  }
)


```

**Comment by pheuter** [comment]
Thanks for the suggestion, makes sense.

**Comment by vmarcosp** [comment]
Can we close? @fakenickels
