### ISSUE TITLE
What is behavior of Startegy OnDemand validation

### ISSUE THREAD

**Issue by enieber** [rescriptbr/reform#217]
In `validationStrategy` has 2 strategy

- OnDemand
- OnChange

What is behaviour expected in OnDemand?

Because the OnChange has validate when change input.

**Comment by vmarcosp** [comment]
OnChange - triggered when happens any changes on the field.
OnDemand - you have to trigger the validation manually by calling `form.validateForm` or `form.validateFields`.

**Comment by vmarcosp** [comment]
I'll close the issue since we answered the question.
We're working on a new version of the documentation that will cover the details of the form strategy.
