### ISSUE TITLE
update to rescript v10

### ISSUE THREAD

**Issue by jauniuseitmantis** [rescriptbr/reform#239]
since [rescript v10](https://rescript-lang.org/blog/release-10-0-0) was released, reform needs to be updated to have the latest version of rescript

**Comment by vmarcosp** [comment]
I'm not sure if we should migrate for the v10 right now.
There are no features that we could use on the library and we should keep supporting the ReScript v9 until we release a breaking change.
I'm using ReForm + ReScript v10 in some production projects and it's working very well.

**Comment by vmarcosp** [comment]
cc @fakenickels

**Comment by vmarcosp** [comment]
Closing since we're not migrating for the v10 yet.
